name: Deploy Theme on OVH

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Checkout du code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}  # Utilise le token ajouté

      # Étape 2 : Déployer le thème via FTP
      - name: Deploy theme via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.OVH_SERVER }}
          username: ${{ secrets.OVH_USERNAME }}
          password: ${{ secrets.OVH_PASSWORD }}  # Ajoutez aussi ce secret dans GitHub
          local-dir: ./
          server-dir: /wp-content/themes/plac/
